### ISSUE TITLE
TF running in the docker

### ISSUE THREAD

**Issue by Boshin** [lakshayg/tensorflow-build-archived#26] opened 2018-03-02 14:01 UTC
I am use TF in docker, the wheel should be installed in host or docker environment?
Please help me, thanks!

**Comment by lakshayg** [comment] 2018-03-02 14:12
I haven't used docker but AFAIK it should support all the instructions your CPU supports. So just use the binary which you would use without docker.

**Comment by lakshayg** [comment] 2018-07-13 08:19
Closing this issue. Feel free to reopen if the problem is still unresolved.

**Closed as completed by lakshayg** 2018-07-13 08:19 UTC
Labels: awaiting reply
