### ISSUE TITLE
tensorflow binaries for windows 10 x64 python 3.6

### ISSUE THREAD

**Issue by zxysilent** [lakshayg/tensorflow-build-archived#18] opened 2017-12-30 03:09 UTC

**Comment by lakshayg** [comment] 2017-12-30 06:01
HI @zxysilent, unfortunately, I do not have a windows machine so cannot build a wheel myself. However, I am willing to help if you would like to try building it on your machine, do let me know. If it works then we can host the binary in this repo as well.

**Comment by zxysilent** [comment] 2018-01-05 09:35
It's too difficult for me

**Comment by h93910** [comment] 2018-01-09 08:22
i also need that, my friend

**Comment by dbskccc** [comment] 2018-01-21 10:16
@lakshayg you can try virtualbox for an windows build

**Comment by lakshayg** [comment] 2018-01-21 10:21
@dbskccc Yes, that can be done but would that be legal? Is windows available for VirtualBox?

**Comment by lakshayg** [comment] 2018-03-06 17:58
I have added a link to TF for windows, see if they work for you. Please close this issue if they work.
https://github.com/fo40225/tensorflow-windows-wheel

**Comment by lakshayg** [comment] 2018-07-13 08:19
Closing this issue. Feel free to reopen if the problem is still unresolved.

**Closed as completed by lakshayg** 2018-07-13 08:19 UTC
Labels: awaiting reply
